
# CI constraints for every branch
workflow:
  rules:
      # Only run if source is an open merge request or a branch push
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

# Include PNNL GitLab stdlib
include:
  # Leverage local copy?
  #- remote: 'https://raw.githubusercontent.com/pnnl-miscscripts/gitlab-lib/v1/gitlab-lib.yaml'
  - local: '/.gitlab/ci/pnnl.gitlab-lib.yml'
  - local: '/.gitlab/ci/pnnl.gitlab-ci.yml'
  - local: '/.gitlab/ci/ornl.gitlab-ci.yml'
