.ornl_script_template: &ornl_script_definition
  script:
    - |
      # Do _not_ clean up WORKDIR as files are needed for testing
      set -xv
      mkdir -p "$WORKDIR"
      cp -R ./* "$WORKDIR"
      cd "$WORKDIR"
      MY_CLUSTER=ascent ./build.sh --build-only || exit 1

.ornl_test_script_template: &ornl_test_script_definition
  script:
    - |
      set -xv
      cd "$WORKDIR"
      MY_CLUSTER="ascent" ./build.sh --test-only
      res=$?
      exit $res
  after_script:
    - |
      cd "$WORKDIR/.."
      rm -rf "$WORKDIR"


.ornl_environment_template: &ornl_environment_variables
  variables:
    SCHEDULER_PARAMETERS: "-P CSC359 -nnodes 1 -W 30"
    WORKDIR: /gpfs/wolf/proj-shared/csc359/ci/${CI_PIPELINE_ID}

.pnnl_script_template: &pnnl_script_definition
  script:
    - |
      set -xv
      #
      #  NOTES:  WORKDIR is on constance/marianas/newell
      #          ./      is only on the Kubernetes instance
      #
      export WORKDIR="$HOME/gitlab/$CI_JOB_ID/"
      mkdir -p "$WORKDIR"
      cp -R ./* "$WORKDIR"
      cd "$WORKDIR"
      # echo submitting batch job
      [ -f output ] && rm output
      touch output
      tail -f output &
      tailpid=$!
      sbatch --export=MY_CLUSTER=$CLUSTER -A EXASGD --gres=gpu:1 -p $SLURM_Q -o output -e output -t 1:00:00 $WORKDIR/build.sh
      res=1
      # Uncomment when we find nondeterministic CI issue.
      # set +xv
      while :;
      do
        if [[ "$(awk 'BEGIN{i=0}/BUILD_STATUS/{i++}END{print i}' output)" != "0" ]]; then
          kill $tailpid
          res=$(grep BUILD_STATUS output | tail -n 1 | cut -f2 -d':')
          break
        fi
        sleep 10
      done
      echo "Finished batch job with exit code: $res"
      #
      #  NOTE:  If the job fails, comment out the line below and cd to
      #         $HOME/gitlab/$CI_JOB_ID and run ./build.sh by hand to
      #         figure out what went wrong.
      # cd $WORKDIR
      # ./BUILD.sh
      #
      rm -rf "$WORKDIR"
      exit $res


.pnnl_tags_template: &pnnl_tags_definition
  tags:
    - k8s
    - ikp
    - exasgd
    - marianas

stages:
  - build
  - test

# For Ascent CI
build_on_login_node:
  stage: build
  tags:
    - nobatch
  rules:
    - if: '$CI_PROJECT_PATH == "ecpcitest/exasgd/exago"'
  <<: *ornl_script_definition
  <<: *ornl_environment_variables

test_on_compute_node:
  stage: test
  dependencies:
    - build_on_login_node
  tags:
    - batch
  rules:
    - if: '$CI_PROJECT_PATH == "ecpcitest/exasgd/exago"'
  <<: *ornl_test_script_definition
  <<: *ornl_environment_variables
# ---

# For PNNL CI
build_on_newell:
  stage: build
  variables:
    SLURM_Q: "newell_shared"
    CLUSTER: "newell"
  <<: *pnnl_tags_definition
  <<: *pnnl_script_definition
  rules:
    - if: '$CI_PROJECT_ROOT_NAMESPACE == "exasgd"'

build_on_marianas:
  stage: build
  variables:
    SLURM_Q: "shared"
    CLUSTER: "marianas"
  <<: *pnnl_tags_definition
  <<: *pnnl_script_definition
  rules:
    - if: '$CI_PROJECT_ROOT_NAMESPACE == "exasgd"'
# ---
